exec-once = waybar
monitor=,preferred,auto,1

$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun

input {
    kb_layout = us,ru
    kb_options = grp:alt_shift_toggle
}

$mainMod = SUPER

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, R, exec, $menu

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Управление громкостью (крутилка / мультимедиа-клавиши)
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

general {
    layout = dwindle
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(7aa2f7ee) rgba(7dcfffee) 45deg
    col.inactive_border = rgba(24283baa)
}

dwindle {
    preserve_split = true
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.9
}

bind = $mainMod, F, fullscreen, 0
bind = $mainMod, V, togglefloating,

# Скриншот выделенной области (как в GNOME по PrtScn)
bind = , Print, exec, grimblast --notify copy area

# Скриншот всего экрана (Shift + PrtScn)
bind = Shift, Print, exec, grimblast --notify copy output

# Скриншот активного окна (Alt + PrtScn)
bind = Alt, Print, exec, grimblast --notify copy active
